secrets:
  postgres_user:
    file: .secrets/postgres_user.txt
  postgres_password:
    file: .secrets/postgres_password.txt
  healthcheck_user:
    file: .secrets/healthcheck_user.txt
  healthcheck_password:
    file: .secrets/healthcheck_password.txt
  lto_app_user:
    file: .secrets/lto_app_user.txt
  lto_app_password:
    file: .secrets/lto_app_password.txt

services:
  backend:
    image: lto-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      LOG_LEVEL: info
      ENVIRONMENT: development
      API_URL: http://backend:8000
      POSTGRES_HOST: storage-postgres
      POSTGRES_USER_FILE: /run/secrets/lto_app_user
      POSTGRES_PASSWORD_FILE: /run/secrets/lto_app_password
    ports:
      - "8000:8000"
    volumes:
      # Hot reload in development.
      - ./backend:/app
    secrets:
      - lto_app_user
      - lto_app_password
    networks:
      - lto_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  storage-postgres:
    image: lto-storage-postgres:latest
    build:
      context: ./storage/postgres
      dockerfile: Dockerfile.postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: lto
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_user
      - postgres_password
      - healthcheck_user
      - healthcheck_password
      - lto_app_user
      - lto_app_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./storage/postgres/initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - lto_network
    healthcheck:
      test: ["CMD-SHELL", "PGUSER=$(cat /run/secrets/healthcheck_user) PGPASSWORD=$(cat /run/secrets/healthcheck_password) pg_isready -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    

  frontend:
    image: lto-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      BACKEND_PUBLIC_API_URL: http://localhost:8000 # API-side URL.
      NODE_ENV: development
    volumes:
      # Hot reload in development.
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - lto_network

networks:
  lto_network:
    driver: bridge
    name: lto_network

volumes:
  postgres_data: {}